version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: knn-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: knn-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
#   db:
#     image: postgres:15
#     container_name: knn-db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

# Deixei comentado o serviço de banco de dados, pois não está sendo utilizado no momento.
# Se precisar, descomente e configure conforme necessário.
