version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: knn-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    container_name: knn-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
